version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal
  wordpress:
    depends_on:
      - database
    image: wordpress:5.4.2-php7.3-apache
    volumes: 
     - ./themes:/var/www/html/wp-content/themes/
     - ./plugins:/var/www/html/wp-content/plugins/
    ports:
     - "8088:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal
      - public
networks:
  internal:
  public: 
